CREATE DATABASE ECOMMERCE

--CREATION OF CUSTOMERS TABLE
CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT IDENTITY PRIMARY KEY,
NAME VARCHAR(30),
EMAIL VARCHAR(40),
PASSWORD VARCHAR(40))

INSERT INTO CUSTOMERS VALUES('SRIDHARSHINI','srivarshicse2004@gmail.com','sri@0114')
INSERT INTO CUSTOMERS VALUES('VARSHINI','varsh2007@gmail.com','varsi_2007')
INSERT INTO CUSTOMERS VALUES('SARANYA','saranyaperiyamsamy@gmail.com','saranya123')
INSERT INTO CUSTOMERS VALUES('THIYANESH','thiyaneshsampath@gmail.com','thiya@123')
INSERT INTO CUSTOMERS VALUES('ARSHITH','arshiththiyanesh@gmail.com','arshithsri@1')

--CREATION OF PRODUCTS TABLE
CREATE TABLE PRODUCTS(
PRODUCT_ID INT IDENTITY PRIMARY KEY,
NAME VARCHAR(30),
PRICE INT,
DESCRIPTION VARCHAR(70),
STOCK_QUANTITY INT)
INSERT INTO products VALUES('ARSHITH',400,'product is so valuable',100)
INSERT INTO products VALUES('HARI',700,'QUALITY IS GOOD',500)
INSERT INTO products VALUES('RISHWANTH',1000,'100% ASSURANCE',70)
INSERT INTO products VALUES('AADHI',1200,'1 YEAR WARRANTY',20)
INSERT INTO products VALUES('ADHVATHIYA',1500,'COST EFFECTIVE',90)


--CREATION OF CART TABLE
CREATE TABLE CART(
CART_ID INT IDENTITY PRIMARY KEY,
CUSTOMER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
FOREIGN KEY(CUSTOMER_ID)REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY(PRODUCT_ID)REFERENCES PRODUCTS(PRODUCT_ID))
INSERT INTO CART VALUES(1,1,90)
INSERT INTO CART VALUES(2,2,70)
INSERT INTO CART VALUES(3,3,60)
INSERT INTO CART VALUES(4,4,30)
INSERT INTO CART VALUES(5,5,100)

--CREATION OF ORDERS TABLE
CREATE TABLE ORDERS(
ORDER_ID INT IDENTITY PRIMARY KEY,
CUSTOMER_ID INT,
ORDER_DATE DATE,
TOTAL_PRICE INT,
SHIPPING_ADDRESS VARCHAR(70),
FOREIGN KEY(CUSTOMER_ID)REFERENCES CUSTOMERS(CUSTOMER_ID))
INSERT INTO ORDERS VALUES(1,'2023-09-18',500,'MURUGAN KOVIL,NAMAKKAL')
INSERT INTO ORDERS VALUES(2,'2024-03-18',1400,'FAIRLANDS,SALEM')
INSERT INTO ORDERS VALUES(3,'2024-07-01',700,'GANAPATHY STREET,ERODE')
--CREATION OF ORDER_ITEMS TABLE
CREATE TABLE ORDER_ITEMS(
ORDER_ITEM_ID INT IDENTITY PRIMARY KEY,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
FOREIGN KEY(ORDER_ID)REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY(PRODUCT_ID)REFERENCES PRODUCTS(PRODUCT_ID))
INSERT INTO ORDER_ITEMS VALUES(1,1,30)
INSERT INTO ORDER_ITEMS VALUES(2,2,90)
INSERT INTO ORDER_ITEMS VALUES(3,3,80)
